server:
    port: 8080

spring:
    rabbitmq:
        host: rabbitmq
        port: 5672
        user: guest
        password: guest
        connection-name-prefix: ms-auth-app

    application:
        name: ms-auth

    data:
        mongodb:
            uri: ${SPRING_DATA_MONGODB_URI}
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: BANTADS-AUTH-API


jwt:
    private-key: file:private-key.pem
    public-key: file:public-key.pem


rabbitmq:
    exchange:
        saga: exchangePrincipal
    queue:
        auth-create: saga.auth.create.queue
    key:
        saga-create-auth: saga.auth.created
        saga-create-success: saga.auth.success
        saga-create-fail: saga.auth.fail