server:
    port: 8080

spring:
    rabbitmq:
        host: rabbitmq
        port: 5672
        user: guest
        password: guest
        connection-name-prefix: ms-auth-app

    application:
        name: ms-auth

    data:
        mongodb:
            uri: ${SPRING_DATA_MONGODB_URI}
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: BANTADS-AUTH-API
    mail:
        host: smtp.gmail.com
        port: 587
        username: dindinbantads@gmail.com
        password: occn bylm ewoy dqhx
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000


jwt:
  public-key: file:/app/public-key.pem
  private-key: file:/app/private-key.pem


#
#management:
#    endpoints:
#        web:
#            exposure:
#                include: "health,info,prometheus"
#    endpoint:
#        health:
#            show-details: always
#    server:
#        port: 9090


rabbitmq:
    exchange:
        saga: exchangePrincipal
    queue:
        auth-create: queue-auth-criar
        auth-rollback: queue-auth-rollback
        auth-approve: queue-auth-aprovar
    key:
        auth-create: keyAuth-criar
        auth-rollback: keyAuth-rollback
        auth-approve: keyAuth-aprovar

        saga-create-success: MsSaga
        saga-create-fail: MsSaga